use crate::gb::opcodes::opcode::OPCode;
use crate::gb::opcodes::opfuncs::op;

pub static  OP_TABLE : [OPCode; 0x100] = [
    ////////////// 0x0x
    OPCode { code: 0x00, size: 4, name: "NOP", func: op::nop}, 
    OPCode { code: 0x01, size:12, name: "LD BC,d16", func: op::unknown},
    OPCode { code: 0x02, size: 8, name: "LD (BC),A", func: op::unknown},
    OPCode { code: 0x03, size: 8, name: "INC BC", func: op::unknown},
    OPCode { code: 0x04, size: 4, name: "INC B", func: op::unknown},
    OPCode { code: 0x05, size: 4, name: "DEC B", func: op::unknown},
    OPCode { code: 0x06, size: 8, name: "LD B,d8", func: op::unknown},
    OPCode { code: 0x07, size: 4, name: "RLCA", func: op::unknown},
    OPCode { code: 0x08, size:20, name: "LD (a16),SP", func: op::unknown},
    OPCode { code: 0x09, size: 8, name: "ADD HL,BC", func: op::unknown},
    OPCode { code: 0x0A, size: 8, name: "LD A,(BC)", func: op::unknown},
    OPCode { code: 0x0B, size: 8, name: "DEC BC", func: op::unknown},
    OPCode { code: 0x0C, size: 4, name: "INC C", func: op::unknown},
    OPCode { code: 0x0D, size: 4, name: "DEC C", func: op::unknown},
    OPCode { code: 0x0E, size: 8, name: "LD C,d8", func: op::unknown},
    OPCode { code: 0x0F, size: 4, name: "RRCA", func: op::unknown},
    ////////////// 0x1x
    OPCode { code: 0x10, size: 4, name: "STOP 0", func: op::unknown}, 
    OPCode { code: 0x11, size:12, name: "LD DE,d16", func: op::unknown},
    OPCode { code: 0x12, size: 8, name: "LD (DE),A", func: op::unknown},
    OPCode { code: 0x13, size: 8, name: "INC DE", func: op::unknown},
    OPCode { code: 0x14, size: 4, name: "INC D", func: op::unknown},
    OPCode { code: 0x15, size: 4, name: "DEC D", func: op::unknown},
    OPCode { code: 0x16, size: 8, name: "LD D,d8", func: op::unknown},
    OPCode { code: 0x17, size: 4, name: "RLA", func: op::unknown},
    OPCode { code: 0x18, size:12, name: "JR r8", func: op::unknown},
    OPCode { code: 0x19, size: 8, name: "ADD HL,DE", func: op::unknown},
    OPCode { code: 0x1A, size: 8, name: "LD A,(DE)", func: op::unknown},
    OPCode { code: 0x1B, size: 8, name: "DEC DE", func: op::unknown},
    OPCode { code: 0x1C, size: 4, name: "INC E", func: op::unknown},
    OPCode { code: 0x1D, size: 4, name: "DEC E", func: op::unknown},
    OPCode { code: 0x1E, size: 8, name: "LD E,d8", func: op::unknown},
    OPCode { code: 0x1F, size: 4, name: "RRA", func: op::unknown},
    ////////////// 0x2x
    OPCode { code: 0x20, size: 2, name: "JR NZ,r8", func: op::unknown}, // Cycles May Vary (8 / 12) 
    OPCode { code: 0x21, size: 3, name: "LD HL,d16", func: op::unknown},
    OPCode { code: 0x22, size: 1, name: "LD (HL+),A", func: op::unknown},
    OPCode { code: 0x23, size: 1, name: "INC HL", func: op::unknown},
    OPCode { code: 0x24, size: 1, name: "INC H", func: op::unknown},
    OPCode { code: 0x25, size: 1, name: "DEC H", func: op::unknown},
    OPCode { code: 0x26, size: 2, name: "LD H,d8", func: op::unknown},
    OPCode { code: 0x27, size: 1, name: "DAA", func: op::unknown},
    OPCode { code: 0x28, size: 2, name: "JR Z,r8", func: op::unknown}, // Cycles May Vary (8 / 12) 
    OPCode { code: 0x29, size: 1, name: "ADD HL,HL", func: op::unknown},
    OPCode { code: 0x2A, size: 1, name: "LD A,(HL+)", func: op::unknown},
    OPCode { code: 0x2B, size: 1, name: "DEC HL", func: op::unknown},
    OPCode { code: 0x2C, size: 1, name: "INC L", func: op::unknown},
    OPCode { code: 0x2D, size: 1, name: "DEC L", func: op::unknown},
    OPCode { code: 0x2E, size: 2, name: "LD L,d8", func: op::unknown},
    OPCode { code: 0x2F, size: 1, name: "CPL", func: op::unknown},
    ////////////// 0x3x
    OPCode { code: 0x30, size: 2, name: "JR NC,r8", func: op::unknown}, // Cycles May Vary (8 / 12) 
    OPCode { code: 0x31, size: 3, name: "LD SP,d16", func: op::unknown},
    OPCode { code: 0x32, size: 1, name: "LD (HL-),A", func: op::unknown},
    OPCode { code: 0x33, size: 1, name: "INC SP", func: op::unknown},
    OPCode { code: 0x34, size: 1, name: "INC (HL)", func: op::unknown},
    OPCode { code: 0x35, size: 1, name: "DEC (HL)", func: op::unknown},
    OPCode { code: 0x36, size: 2, name: "LD (HL),d8", func: op::unknown},
    OPCode { code: 0x37, size: 1, name: "SCF", func: op::unknown},
    OPCode { code: 0x38, size: 2, name: "JR C,r8", func: op::unknown}, // Cycles May Vary (8 / 12) 
    OPCode { code: 0x39, size: 1, name: "ADD HL,SP", func: op::unknown},
    OPCode { code: 0x3A, size: 1, name: "LD A,(HL-)", func: op::unknown},
    OPCode { code: 0x3B, size: 1, name: "DEC SP", func: op::unknown},
    OPCode { code: 0x3C, size: 1, name: "INC A", func: op::unknown},
    OPCode { code: 0x3D, size: 1, name: "DEC A", func: op::unknown},
    OPCode { code: 0x3E, size: 2, name: "LD A,d8", func: op::unknown},
    OPCode { code: 0x3F, size: 1, name: "CCF", func: op::unknown},
    ////////////// 0x4x
    OPCode { code: 0x40, size: 1, name: "LD B,B", func: op::unknown}, 
    OPCode { code: 0x41, size: 1, name: "LD B,C", func: op::unknown},
    OPCode { code: 0x42, size: 1, name: "LD B,D", func: op::unknown},
    OPCode { code: 0x43, size: 1, name: "LD B,E", func: op::unknown},
    OPCode { code: 0x44, size: 1, name: "LD B,H", func: op::unknown},
    OPCode { code: 0x45, size: 1, name: "LD B,L", func: op::unknown},
    OPCode { code: 0x46, size: 1, name: "LD B,(HL)", func: op::unknown},
    OPCode { code: 0x47, size: 1, name: "LD B,A", func: op::unknown},
    OPCode { code: 0x48, size: 1, name: "LD C,B", func: op::unknown},
    OPCode { code: 0x49, size: 1, name: "LD C,C", func: op::unknown},
    OPCode { code: 0x4A, size: 1, name: "LD C,D", func: op::unknown},
    OPCode { code: 0x4B, size: 1, name: "LD C,E", func: op::unknown},
    OPCode { code: 0x4C, size: 1, name: "LD C,H", func: op::unknown},
    OPCode { code: 0x4D, size: 1, name: "LD C,L", func: op::unknown},
    OPCode { code: 0x4E, size: 1, name: "LD C,(HL)", func: op::unknown},
    OPCode { code: 0x4F, size: 1, name: "LD C,A", func: op::unknown},
    ////////////// 0x5x
    OPCode { code: 0x50, size: 1, name: "LD D,B", func: op::unknown}, 
    OPCode { code: 0x51, size: 1, name: "LD D,C", func: op::unknown},
    OPCode { code: 0x52, size: 1, name: "LD D,D", func: op::unknown},
    OPCode { code: 0x53, size: 1, name: "LD D,E", func: op::unknown},
    OPCode { code: 0x54, size: 1, name: "LD D,H", func: op::unknown},
    OPCode { code: 0x55, size: 1, name: "LD D,L", func: op::unknown},
    OPCode { code: 0x56, size: 1, name: "LD D,(HL)", func: op::unknown},
    OPCode { code: 0x57, size: 1, name: "LD D,A", func: op::unknown},
    OPCode { code: 0x58, size: 1, name: "LD E,B", func: op::unknown},
    OPCode { code: 0x59, size: 1, name: "LD E,C", func: op::unknown},
    OPCode { code: 0x5A, size: 1, name: "LD E,D", func: op::unknown},
    OPCode { code: 0x5B, size: 1, name: "LD E,E", func: op::unknown},
    OPCode { code: 0x5C, size: 1, name: "LD E,H", func: op::unknown},
    OPCode { code: 0x5D, size: 1, name: "LD E,L", func: op::unknown},
    OPCode { code: 0x5E, size: 1, name: "LD E,(HL)", func: op::unknown},
    OPCode { code: 0x5F, size: 1, name: "LD E,A", func: op::unknown},
    ////////////// 0x6x
    OPCode { code: 0x60, size: 1, name: "LD H,B", func: op::unknown}, 
    OPCode { code: 0x61, size: 1, name: "LD H,C", func: op::unknown},
    OPCode { code: 0x62, size: 1, name: "LD H,D", func: op::unknown},
    OPCode { code: 0x63, size: 1, name: "LD H,E", func: op::unknown},
    OPCode { code: 0x64, size: 1, name: "LD H,H", func: op::unknown},
    OPCode { code: 0x65, size: 1, name: "LD H,L", func: op::unknown},
    OPCode { code: 0x66, size: 1, name: "LD H,(HL)", func: op::unknown},
    OPCode { code: 0x67, size: 1, name: "LD H,A", func: op::unknown},
    OPCode { code: 0x68, size: 1, name: "LD L,B", func: op::unknown},
    OPCode { code: 0x69, size: 1, name: "LD L,C", func: op::unknown},
    OPCode { code: 0x6A, size: 1, name: "LD L,D", func: op::unknown},
    OPCode { code: 0x6B, size: 1, name: "LD L,E", func: op::unknown},
    OPCode { code: 0x6C, size: 1, name: "LD L,H", func: op::unknown},
    OPCode { code: 0x6D, size: 1, name: "LD L,L", func: op::unknown},
    OPCode { code: 0x6E, size: 1, name: "LD L,(HL)", func: op::unknown},
    OPCode { code: 0x6F, size: 1, name: "LD L,A", func: op::unknown},
    ////////////// 0x7x
    OPCode { code: 0x70, size: 1, name: "LD B,B", func: op::unknown}, 
    OPCode { code: 0x71, size: 1, name: "LD B,C", func: op::unknown},
    OPCode { code: 0x72, size: 1, name: "LD B,D", func: op::unknown},
    OPCode { code: 0x73, size: 1, name: "LD B,E", func: op::unknown},
    OPCode { code: 0x74, size: 1, name: "LD B,H", func: op::unknown},
    OPCode { code: 0x75, size: 1, name: "LD B,L", func: op::unknown},
    OPCode { code: 0x76, size: 1, name: "LD B,(HL)", func: op::unknown},
    OPCode { code: 0x77, size: 1, name: "LD B,A", func: op::unknown},
    OPCode { code: 0x78, size: 1, name: "LD C,B", func: op::unknown},
    OPCode { code: 0x79, size: 1, name: "LD C,C", func: op::unknown},
    OPCode { code: 0x7A, size: 1, name: "LD C,D", func: op::unknown},
    OPCode { code: 0x7B, size: 1, name: "LD C,E", func: op::unknown},
    OPCode { code: 0x7C, size: 1, name: "LD C,H", func: op::unknown},
    OPCode { code: 0x7D, size: 1, name: "LD C,L", func: op::unknown},
    OPCode { code: 0x7E, size: 1, name: "LD C,(HL)", func: op::unknown},
    OPCode { code: 0x7F, size: 1, name: "LD C,A", func: op::unknown},
    ////////////// 0x8x
    OPCode { code: 0x80, size: 1, name: "ADD A,B", func: op::unknown}, 
    OPCode { code: 0x81, size: 1, name: "ADD A,C", func: op::unknown},
    OPCode { code: 0x82, size: 1, name: "ADD A,D", func: op::unknown},
    OPCode { code: 0x83, size: 1, name: "ADD A,E", func: op::unknown},
    OPCode { code: 0x84, size: 1, name: "ADD A,H", func: op::unknown},
    OPCode { code: 0x85, size: 1, name: "ADD A,L", func: op::unknown},
    OPCode { code: 0x86, size: 1, name: "ADD A,(HL)", func: op::unknown},
    OPCode { code: 0x87, size: 1, name: "ADD A,A", func: op::unknown},
    OPCode { code: 0x88, size: 1, name: "ADC A,B", func: op::unknown},
    OPCode { code: 0x89, size: 1, name: "ADC A,C", func: op::unknown},
    OPCode { code: 0x8A, size: 1, name: "ADC A,D", func: op::unknown},
    OPCode { code: 0x8B, size: 1, name: "ADC A,E", func: op::unknown},
    OPCode { code: 0x8C, size: 1, name: "ADC A,H", func: op::unknown},
    OPCode { code: 0x8D, size: 1, name: "ADC A,L", func: op::unknown},
    OPCode { code: 0x8E, size: 1, name: "ADC A,(HL)", func: op::unknown},
    OPCode { code: 0x8F, size: 1, name: "ADC A,A", func: op::unknown},
    ////////////// 0x9x
    OPCode { code: 0x90, size: 1, name: "SUB B", func: op::unknown}, 
    OPCode { code: 0x91, size: 1, name: "SUB C", func: op::unknown},
    OPCode { code: 0x92, size: 1, name: "SUB D", func: op::unknown},
    OPCode { code: 0x93, size: 1, name: "SUB E", func: op::unknown},
    OPCode { code: 0x94, size: 1, name: "SUB H", func: op::unknown},
    OPCode { code: 0x95, size: 1, name: "SUB L", func: op::unknown},
    OPCode { code: 0x96, size: 1, name: "SUB (HL)", func: op::unknown},
    OPCode { code: 0x97, size: 1, name: "SUB A", func: op::unknown},
    OPCode { code: 0x98, size: 1, name: "SBC A,B", func: op::unknown},
    OPCode { code: 0x99, size: 1, name: "SBC A,C", func: op::unknown},
    OPCode { code: 0x9A, size: 1, name: "SBC A,D", func: op::unknown},
    OPCode { code: 0x9B, size: 1, name: "SBC A,E", func: op::unknown},
    OPCode { code: 0x9C, size: 1, name: "SBC A,H", func: op::unknown},
    OPCode { code: 0x9D, size: 1, name: "SBC A,L", func: op::unknown},
    OPCode { code: 0x9E, size: 1, name: "SBC A,(HL)", func: op::unknown},
    OPCode { code: 0x9F, size: 1, name: "SBC A,A", func: op::unknown},
    ////////////// 0xAx
    OPCode { code: 0xA0, size: 1, name: "AND B", func: op::unknown}, 
    OPCode { code: 0xA1, size: 1, name: "AND C", func: op::unknown},
    OPCode { code: 0xA2, size: 1, name: "AND D", func: op::unknown},
    OPCode { code: 0xA3, size: 1, name: "AND E", func: op::unknown},
    OPCode { code: 0xA4, size: 1, name: "AND H", func: op::unknown},
    OPCode { code: 0xA5, size: 1, name: "AND L", func: op::unknown},
    OPCode { code: 0xA6, size: 1, name: "AND (HL)", func: op::unknown},
    OPCode { code: 0xA7, size: 1, name: "AND A", func: op::unknown},
    OPCode { code: 0xA8, size: 1, name: "XOR B", func: op::unknown},
    OPCode { code: 0xA9, size: 1, name: "XOR C", func: op::unknown},
    OPCode { code: 0xAA, size: 1, name: "XOR D", func: op::unknown},
    OPCode { code: 0xAB, size: 1, name: "XOR E", func: op::unknown},
    OPCode { code: 0xAC, size: 1, name: "XOR H", func: op::unknown},
    OPCode { code: 0xAD, size: 1, name: "XOR L", func: op::unknown},
    OPCode { code: 0xAE, size: 1, name: "XOR (HL)", func: op::unknown},
    OPCode { code: 0xAF, size: 1, name: "XOR A", func: op::unknown},
    ////////////// 0xBx
    OPCode { code: 0xB0, size: 1, name: "OR B", func: op::unknown}, 
    OPCode { code: 0xB1, size: 1, name: "OR C", func: op::unknown},
    OPCode { code: 0xB2, size: 1, name: "OR D", func: op::unknown},
    OPCode { code: 0xB3, size: 1, name: "OR E", func: op::unknown},
    OPCode { code: 0xB4, size: 1, name: "OR H", func: op::unknown},
    OPCode { code: 0xB5, size: 1, name: "OR L", func: op::unknown},
    OPCode { code: 0xB6, size: 1, name: "OR (HL)", func: op::unknown},
    OPCode { code: 0xB7, size: 1, name: "OR A", func: op::unknown},
    OPCode { code: 0xB8, size: 1, name: "CP B", func: op::unknown},
    OPCode { code: 0xB9, size: 1, name: "CP C", func: op::unknown},
    OPCode { code: 0xBA, size: 1, name: "CP D", func: op::unknown},
    OPCode { code: 0xBB, size: 1, name: "CP E", func: op::unknown},
    OPCode { code: 0xBC, size: 1, name: "CP H", func: op::unknown},
    OPCode { code: 0xBD, size: 1, name: "CP L", func: op::unknown},
    OPCode { code: 0xBE, size: 1, name: "CP (HL)", func: op::unknown},
    OPCode { code: 0xBF, size: 1, name: "CP A", func: op::unknown},
    ////////////// 0xCx
    OPCode { code: 0xC0, size: 1, name: "RET NZ", func: op::unknown},
    OPCode { code: 0xC1, size: 2, name: "POP BC", func: op::unknown},
    OPCode { code: 0xC2, size: 3, name: "JP NZ,a16", func: op::unknown},
    OPCode { code: 0xC3, size: 3, name: "JP a16", func: op::unknown},
    OPCode { code: 0xC4, size: 3, name: "CALL NZ,a16", func: op::unknown},
    OPCode { code: 0xC5, size: 1, name: "PUSH BC", func: op::unknown},
    OPCode { code: 0xC6, size: 2, name: "ADD A,d8", func: op::unknown},
    OPCode { code: 0xC7, size: 1, name: "RST 00H", func: op::unknown},
    OPCode { code: 0xC8, size: 1, name: "RET Z", func: op::unknown},
    OPCode { code: 0xC9, size: 1, name: "RET", func: op::unknown},
    OPCode { code: 0xCA, size: 3, name: "JP Z,a16", func: op::unknown},
    OPCode { code: 0xCB, size: 1, name: "PREFIX CB", func: op::prefix_cb},
    OPCode { code: 0xCC, size: 3, name: "CALL Z,a16", func: op::unknown},
    OPCode { code: 0xCD, size: 3, name: "CALL a16", func: op::unknown}, 
    OPCode { code: 0xCE, size: 2, name: "ADC A,d8", func: op::unknown},
    OPCode { code: 0xCF, size: 1, name: "RST 08H", func: op::unknown},
    ////////////// 0xDx
    OPCode { code: 0xD0, size: 1, name: "RET NC", func: op::unknown},
    OPCode { code: 0xD1, size: 1, name: "POP DE", func: op::unknown},
    OPCode { code: 0xD2, size: 3, name: "JP NC,a16", func: op::unknown},
    OPCode { code: 0xD3, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xD4, size: 3, name: "CALL NC,a16", func: op::unknown},
    OPCode { code: 0xD5, size: 1, name: "PUSH DE", func: op::unknown},
    OPCode { code: 0xD6, size: 2, name: "SUB d8", func: op::unknown},
    OPCode { code: 0xD7, size: 1, name: "RST 10H", func: op::unknown},
    OPCode { code: 0xD8, size: 1, name: "RET C", func: op::unknown},
    OPCode { code: 0xD9, size: 1, name: "RET C", func: op::unknown},
    OPCode { code: 0xDA, size: 3, name: "JP C,a16", func: op::unknown},
    OPCode { code: 0xDB, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xDC, size: 3, name: "CALL C,a16", func: op::unknown},
    OPCode { code: 0xDD, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xDE, size: 2, name: "SBC A,d8", func: op::unknown},
    OPCode { code: 0xDF, size: 1, name: "RST 18H", func: op::unknown},
    ////////////// 0xEx
    OPCode { code: 0xE0, size: 2, name: "LDH (a8),A", func: op::unknown}, 
    OPCode { code: 0xE1, size: 1, name: "POP HL", func: op::unknown},
    OPCode { code: 0xE2, size: 2, name: "LD (C),A", func: op::unknown},
    OPCode { code: 0xE3, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xE4, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xE5, size: 1, name: "PUSH HL", func: op::unknown},
    OPCode { code: 0xE6, size: 2, name: "AND d8", func: op::unknown},
    OPCode { code: 0xE7, size: 1, name: "RST 20H", func: op::unknown},
    OPCode { code: 0xE8, size: 2, name: "ADD SP,r8", func: op::unknown},
    OPCode { code: 0xE9, size: 1, name: "JP (HL)", func: op::unknown},
    OPCode { code: 0xEA, size: 3, name: "LD (a16),A", func: op::unknown},
    OPCode { code: 0xEB, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xEC, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xED, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xEE, size: 2, name: "XOR d8", func: op::unknown},
    OPCode { code: 0xEF, size: 1, name: "RST 28H", func: op::unknown},
    ////////////// 0xFx
    OPCode { code: 0xF0, size: 2, name: "LDH A,(a8)", func: op::unknown}, 
    OPCode { code: 0xF1, size: 1, name: "POP AF", func: op::unknown},
    OPCode { code: 0xF2, size: 2, name: "LD A,(C)", func: op::unknown},
    OPCode { code: 0xF3, size: 1, name: "DI", func: op::unknown},
    OPCode { code: 0xF4, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xF5, size: 1, name: "PUSH AF", func: op::unknown},
    OPCode { code: 0xF6, size: 2, name: "OR d8", func: op::unknown},
    OPCode { code: 0xF7, size: 1, name: "RST 30H", func: op::unknown},
    OPCode { code: 0xF8, size: 2, name: "LD HL,SP+r8", func: op::unknown},
    OPCode { code: 0xF9, size: 1, name: "LD SP,HL", func: op::unknown},
    OPCode { code: 0xFA, size: 3, name: "LD A,(a16)", func: op::unknown},
    OPCode { code: 0xFB, size: 1, name: "EI", func: op::unknown},
    OPCode { code: 0xFC, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xFD, size: 0, name: "UNUSED", func: op::unused},
    OPCode { code: 0xFE, size: 2, name: "CP d8", func: op::unknown},
    OPCode { code: 0xFF, size: 1, name: "RST 38H", func: op::unknown},
];


pub static CB_OP_TABLE : [OPCode; 0x100] = [
    ////////////// 0x0x
    OPCode { code: 0x00, size: 2, name: "RLC B", func: op::unknown}, 
    OPCode { code: 0x01, size: 2, name: "RLC C", func: op::unknown},
    OPCode { code: 0x02, size: 2, name: "RLC D", func: op::unknown},
    OPCode { code: 0x03, size: 2, name: "RLC E", func: op::unknown},
    OPCode { code: 0x04, size: 2, name: "RLC H", func: op::unknown},
    OPCode { code: 0x05, size: 2, name: "RLC L", func: op::unknown},
    OPCode { code: 0x06, size: 2, name: "RLC (HL)", func: op::unknown},
    OPCode { code: 0x07, size: 2, name: "RLC A", func: op::unknown},
    OPCode { code: 0x08, size: 2, name: "RRC B", func: op::unknown},
    OPCode { code: 0x09, size: 2, name: "RRC C", func: op::unknown},
    OPCode { code: 0x0A, size: 2, name: "RRC D", func: op::unknown},
    OPCode { code: 0x0B, size: 2, name: "RRC E", func: op::unknown},
    OPCode { code: 0x0C, size: 2, name: "RRC H", func: op::unknown},
    OPCode { code: 0x0D, size: 2, name: "RRC L", func: op::unknown},
    OPCode { code: 0x0E, size: 2, name: "RRC (HL)", func: op::unknown},
    OPCode { code: 0x0F, size: 2, name: "RRC A", func: op::unknown},
    ////////////// 0x1x
    OPCode { code: 0x10, size: 2, name: "RL B", func: op::unknown}, 
    OPCode { code: 0x11, size: 2, name: "RL C", func: op::unknown},
    OPCode { code: 0x12, size: 2, name: "RL D", func: op::unknown},
    OPCode { code: 0x13, size: 2, name: "RL E", func: op::unknown},
    OPCode { code: 0x14, size: 2, name: "RL H", func: op::unknown},
    OPCode { code: 0x15, size: 2, name: "RL L", func: op::unknown},
    OPCode { code: 0x16, size: 2, name: "RL (HL)", func: op::unknown},
    OPCode { code: 0x17, size: 2, name: "RL A", func: op::unknown},
    OPCode { code: 0x18, size: 2, name: "RR B", func: op::unknown},
    OPCode { code: 0x19, size: 2, name: "RR C", func: op::unknown},
    OPCode { code: 0x1A, size: 2, name: "RR D", func: op::unknown},
    OPCode { code: 0x1B, size: 2, name: "RR E", func: op::unknown},
    OPCode { code: 0x1C, size: 2, name: "RR H", func: op::unknown},
    OPCode { code: 0x1D, size: 2, name: "RR L", func: op::unknown},
    OPCode { code: 0x1E, size: 2, name: "RR (HL)", func: op::unknown},
    OPCode { code: 0x1F, size: 2, name: "RR A", func: op::unknown},
    ////////////// 0x2x
    OPCode { code: 0x20, size: 2, name: "SLA B", func: op::unknown}, 
    OPCode { code: 0x21, size: 2, name: "SLA C", func: op::unknown},
    OPCode { code: 0x22, size: 2, name: "SLA D", func: op::unknown},
    OPCode { code: 0x23, size: 2, name: "SLA E", func: op::unknown},
    OPCode { code: 0x24, size: 2, name: "SLA H", func: op::unknown},
    OPCode { code: 0x25, size: 2, name: "SLA L", func: op::unknown},
    OPCode { code: 0x26, size: 2, name: "SLA (HL)", func: op::unknown},
    OPCode { code: 0x27, size: 2, name: "SLA A", func: op::unknown},
    OPCode { code: 0x28, size: 2, name: "SRA B", func: op::unknown},
    OPCode { code: 0x29, size: 2, name: "SRA C", func: op::unknown},
    OPCode { code: 0x2A, size: 2, name: "SRA D", func: op::unknown},
    OPCode { code: 0x2B, size: 2, name: "SRA E", func: op::unknown},
    OPCode { code: 0x2C, size: 2, name: "SRA H", func: op::unknown},
    OPCode { code: 0x2D, size: 2, name: "SRA L", func: op::unknown},
    OPCode { code: 0x2E, size: 2, name: "SRA (HL)", func: op::unknown},
    OPCode { code: 0x2F, size: 2, name: "SRA A", func: op::unknown},
    ////////////// 0x3x
    OPCode { code: 0x30, size: 2, name: "SWAP B", func: op::unknown}, 
    OPCode { code: 0x31, size: 2, name: "SWAP C", func: op::unknown},
    OPCode { code: 0x32, size: 2, name: "SWAP D", func: op::unknown},
    OPCode { code: 0x33, size: 2, name: "SWAP E", func: op::unknown},
    OPCode { code: 0x34, size: 2, name: "SWAP H", func: op::unknown},
    OPCode { code: 0x35, size: 2, name: "SWAP L", func: op::unknown},
    OPCode { code: 0x36, size: 2, name: "SWAP (HL)", func: op::unknown},
    OPCode { code: 0x37, size: 2, name: "SWAP A", func: op::unknown},
    OPCode { code: 0x38, size: 2, name: "SRL B", func: op::unknown},
    OPCode { code: 0x39, size: 2, name: "SRL C", func: op::unknown},
    OPCode { code: 0x3A, size: 2, name: "SRL D", func: op::unknown},
    OPCode { code: 0x3B, size: 2, name: "SRL E", func: op::unknown},
    OPCode { code: 0x3C, size: 2, name: "SRL H", func: op::unknown},
    OPCode { code: 0x3D, size: 2, name: "SRL L", func: op::unknown},
    OPCode { code: 0x3E, size: 2, name: "SRL (HL)", func: op::unknown},
    OPCode { code: 0x3F, size: 2, name: "SRL A", func: op::unknown},
    ////////////// 0x4x
    OPCode { code: 0x40, size: 2, name: "BIT 0,B", func: op::unknown}, 
    OPCode { code: 0x41, size: 2, name: "BIT 0,C", func: op::unknown},
    OPCode { code: 0x42, size: 2, name: "BIT 0,D", func: op::unknown},
    OPCode { code: 0x43, size: 2, name: "BIT 0,E", func: op::unknown},
    OPCode { code: 0x44, size: 2, name: "BIT 0,H", func: op::unknown},
    OPCode { code: 0x45, size: 2, name: "BIT 0,L", func: op::unknown},
    OPCode { code: 0x46, size: 2, name: "BIT 0,(HL)", func: op::unknown},
    OPCode { code: 0x47, size: 2, name: "BIT 0,A", func: op::unknown},
    OPCode { code: 0x48, size: 2, name: "BIT 1,B", func: op::unknown},
    OPCode { code: 0x49, size: 2, name: "BIT 1,C", func: op::unknown},
    OPCode { code: 0x4A, size: 2, name: "BIT 1,D", func: op::unknown},
    OPCode { code: 0x4B, size: 2, name: "BIT 1,E", func: op::unknown},
    OPCode { code: 0x4C, size: 2, name: "BIT 1,H", func: op::unknown},
    OPCode { code: 0x4D, size: 2, name: "BIT 1,L", func: op::unknown},
    OPCode { code: 0x4E, size: 2, name: "BIT 1,(HL)", func: op::unknown},
    OPCode { code: 0x4F, size: 2, name: "BIT 1,A", func: op::unknown},
    ////////////// 0x5x
    OPCode { code: 0x50, size: 2, name: "BIT 2,B", func: op::unknown}, 
    OPCode { code: 0x51, size: 2, name: "BIT 2,C", func: op::unknown},
    OPCode { code: 0x52, size: 2, name: "BIT 2,D", func: op::unknown},
    OPCode { code: 0x53, size: 2, name: "BIT 2,E", func: op::unknown},
    OPCode { code: 0x54, size: 2, name: "BIT 2,H", func: op::unknown},
    OPCode { code: 0x55, size: 2, name: "BIT 2,L", func: op::unknown},
    OPCode { code: 0x56, size: 2, name: "BIT 2,(HL)", func: op::unknown},
    OPCode { code: 0x57, size: 2, name: "BIT 2,A", func: op::unknown},
    OPCode { code: 0x58, size: 2, name: "BIT 3,B", func: op::unknown},
    OPCode { code: 0x59, size: 2, name: "BIT 3,C", func: op::unknown},
    OPCode { code: 0x5A, size: 2, name: "BIT 3,D", func: op::unknown},
    OPCode { code: 0x5B, size: 2, name: "BIT 3,E", func: op::unknown},
    OPCode { code: 0x5C, size: 2, name: "BIT 3,H", func: op::unknown},
    OPCode { code: 0x5D, size: 2, name: "BIT 3,L", func: op::unknown},
    OPCode { code: 0x5E, size: 2, name: "BIT 3,(HL)", func: op::unknown},
    OPCode { code: 0x5F, size: 2, name: "BIT 3,A", func: op::unknown},
    ////////////// 0x6x
    OPCode { code: 0x60, size: 2, name: "BIT 4,B", func: op::unknown}, 
    OPCode { code: 0x61, size: 2, name: "BIT 4,C", func: op::unknown},
    OPCode { code: 0x62, size: 2, name: "BIT 4,D", func: op::unknown},
    OPCode { code: 0x63, size: 2, name: "BIT 4,E", func: op::unknown},
    OPCode { code: 0x64, size: 2, name: "BIT 4,H", func: op::unknown},
    OPCode { code: 0x65, size: 2, name: "BIT 4,L", func: op::unknown},
    OPCode { code: 0x66, size: 2, name: "BIT 4,(HL)", func: op::unknown},
    OPCode { code: 0x67, size: 2, name: "BIT 4,A", func: op::unknown},
    OPCode { code: 0x68, size: 2, name: "BIT 5,B", func: op::unknown},
    OPCode { code: 0x69, size: 2, name: "BIT 5,C", func: op::unknown},
    OPCode { code: 0x6A, size: 2, name: "BIT 5,D", func: op::unknown},
    OPCode { code: 0x6B, size: 2, name: "BIT 5,E", func: op::unknown},
    OPCode { code: 0x6C, size: 2, name: "BIT 5,H", func: op::unknown},
    OPCode { code: 0x6D, size: 2, name: "BIT 5,L", func: op::unknown},
    OPCode { code: 0x6E, size: 2, name: "BIT 5,(HL)", func: op::unknown},
    OPCode { code: 0x6F, size: 2, name: "BIT 5,A", func: op::unknown},
    ////////////// 0x7x
    OPCode { code: 0x70, size: 2, name: "BIT 6,B", func: op::unknown}, 
    OPCode { code: 0x71, size: 2, name: "BIT 6,C", func: op::unknown},
    OPCode { code: 0x72, size: 2, name: "BIT 6,D", func: op::unknown},
    OPCode { code: 0x73, size: 2, name: "BIT 6,E", func: op::unknown},
    OPCode { code: 0x74, size: 2, name: "BIT 6,H", func: op::unknown},
    OPCode { code: 0x75, size: 2, name: "BIT 6,L", func: op::unknown},
    OPCode { code: 0x76, size: 2, name: "BIT 6,(HL)", func: op::unknown},
    OPCode { code: 0x77, size: 2, name: "BIT 6,A", func: op::unknown},
    OPCode { code: 0x78, size: 2, name: "BIT 7,B", func: op::unknown},
    OPCode { code: 0x79, size: 2, name: "BIT 7,C", func: op::unknown},
    OPCode { code: 0x7A, size: 2, name: "BIT 7,D", func: op::unknown},
    OPCode { code: 0x7B, size: 2, name: "BIT 7,E", func: op::unknown},
    OPCode { code: 0x7C, size: 2, name: "BIT 7,H", func: op::unknown},
    OPCode { code: 0x7D, size: 2, name: "BIT 7,L", func: op::unknown},
    OPCode { code: 0x7E, size: 2, name: "BIT 7,(HL)", func: op::unknown},
    OPCode { code: 0x7F, size: 2, name: "BIT 7,A", func: op::unknown},
    ////////////// 0x8x
    OPCode { code: 0x80, size: 2, name: "RES 0,B", func: op::unknown}, 
    OPCode { code: 0x81, size: 2, name: "RES 0,C", func: op::unknown},
    OPCode { code: 0x82, size: 2, name: "RES 0,D", func: op::unknown},
    OPCode { code: 0x83, size: 2, name: "RES 0,E", func: op::unknown},
    OPCode { code: 0x84, size: 2, name: "RES 0,H", func: op::unknown},
    OPCode { code: 0x85, size: 2, name: "RES 0,L", func: op::unknown},
    OPCode { code: 0x86, size: 2, name: "RES 0,(HL)", func: op::unknown},
    OPCode { code: 0x87, size: 2, name: "RES 0,A", func: op::unknown},
    OPCode { code: 0x88, size: 2, name: "RES 1,B", func: op::unknown},
    OPCode { code: 0x89, size: 2, name: "RES 1,C", func: op::unknown},
    OPCode { code: 0x8A, size: 2, name: "RES 1,D", func: op::unknown},
    OPCode { code: 0x8B, size: 2, name: "RES 1,E", func: op::unknown},
    OPCode { code: 0x8C, size: 2, name: "RES 1,H", func: op::unknown},
    OPCode { code: 0x8D, size: 2, name: "RES 1,L", func: op::unknown},
    OPCode { code: 0x8E, size: 2, name: "RES 1,(HL)", func: op::unknown},
    OPCode { code: 0x8F, size: 2, name: "RES 1,A", func: op::unknown},
    ////////////// 0x9x
    OPCode { code: 0x90, size: 2, name: "RES 2,B", func: op::unknown}, 
    OPCode { code: 0x91, size: 2, name: "RES 2,C", func: op::unknown},
    OPCode { code: 0x92, size: 2, name: "RES 2,D", func: op::unknown},
    OPCode { code: 0x93, size: 2, name: "RES 2,E", func: op::unknown},
    OPCode { code: 0x94, size: 2, name: "RES 2,H", func: op::unknown},
    OPCode { code: 0x95, size: 2, name: "RES 2,L", func: op::unknown},
    OPCode { code: 0x96, size: 2, name: "RES 2,(HL)", func: op::unknown},
    OPCode { code: 0x97, size: 2, name: "RES 2,A", func: op::unknown},
    OPCode { code: 0x98, size: 2, name: "RES 3,B", func: op::unknown},
    OPCode { code: 0x99, size: 2, name: "RES 3,C", func: op::unknown},
    OPCode { code: 0x9A, size: 2, name: "RES 3,D", func: op::unknown},
    OPCode { code: 0x9B, size: 2, name: "RES 3,E", func: op::unknown},
    OPCode { code: 0x9C, size: 2, name: "RES 3,H", func: op::unknown},
    OPCode { code: 0x9D, size: 2, name: "RES 3,L", func: op::unknown},
    OPCode { code: 0x9E, size: 2, name: "RES 3,(HL)", func: op::unknown},
    OPCode { code: 0x9F, size: 2, name: "RES 3,A", func: op::unknown},
    ////////////// 0xAx
    OPCode { code: 0xA0, size: 2, name: "RES 4,B", func: op::unknown}, 
    OPCode { code: 0xA1, size: 2, name: "RES 4,C", func: op::unknown},
    OPCode { code: 0xA2, size: 2, name: "RES 4,D", func: op::unknown},
    OPCode { code: 0xA3, size: 2, name: "RES 4,E", func: op::unknown},
    OPCode { code: 0xA4, size: 2, name: "RES 4,H", func: op::unknown},
    OPCode { code: 0xA5, size: 2, name: "RES 4,L", func: op::unknown},
    OPCode { code: 0xA6, size: 2, name: "RES 4,(HL)", func: op::unknown},
    OPCode { code: 0xA7, size: 2, name: "RES 4,A", func: op::unknown},
    OPCode { code: 0xA8, size: 2, name: "RES 5,B", func: op::unknown},
    OPCode { code: 0xA9, size: 2, name: "RES 5,C", func: op::unknown},
    OPCode { code: 0xAA, size: 2, name: "RES 5,D", func: op::unknown},
    OPCode { code: 0xAB, size: 2, name: "RES 5,E", func: op::unknown},
    OPCode { code: 0xAC, size: 2, name: "RES 5,H", func: op::unknown},
    OPCode { code: 0xAD, size: 2, name: "RES 5,L", func: op::unknown},
    OPCode { code: 0xAE, size: 2, name: "RES 5,(HL)", func: op::unknown},
    OPCode { code: 0xAF, size: 2, name: "RES 5,A", func: op::unknown},
    ////////////// 0xBx
    OPCode { code: 0xB0, size: 2, name: "RES 6,B", func: op::unknown}, 
    OPCode { code: 0xB1, size: 2, name: "RES 6,C", func: op::unknown},
    OPCode { code: 0xB2, size: 2, name: "RES 6,D", func: op::unknown},
    OPCode { code: 0xB3, size: 2, name: "RES 6,E", func: op::unknown},
    OPCode { code: 0xB4, size: 2, name: "RES 6,H", func: op::unknown},
    OPCode { code: 0xB5, size: 2, name: "RES 6,L", func: op::unknown},
    OPCode { code: 0xB6, size: 2, name: "RES 6,(HL)", func: op::unknown},
    OPCode { code: 0xB7, size: 2, name: "RES 6,A", func: op::unknown},
    OPCode { code: 0xB8, size: 2, name: "RES 7,B", func: op::unknown},
    OPCode { code: 0xB9, size: 2, name: "RES 7,C", func: op::unknown},
    OPCode { code: 0xBA, size: 2, name: "RES 7,D", func: op::unknown},
    OPCode { code: 0xBB, size: 2, name: "RES 7,E", func: op::unknown},
    OPCode { code: 0xBC, size: 2, name: "RES 7,H", func: op::unknown},
    OPCode { code: 0xBD, size: 2, name: "RES 7,L", func: op::unknown},
    OPCode { code: 0xBE, size: 2, name: "RES 7,(HL)", func: op::unknown},
    OPCode { code: 0xBF, size: 2, name: "RES 7,A", func: op::unknown},
    ////////////// 0xCx
    OPCode { code: 0xC0, size: 2, name: "SET 0,B", func: op::unknown}, 
    OPCode { code: 0xC1, size: 2, name: "SET 0,C", func: op::unknown},
    OPCode { code: 0xC2, size: 2, name: "SET 0,D", func: op::unknown},
    OPCode { code: 0xC3, size: 2, name: "SET 0,E", func: op::unknown},
    OPCode { code: 0xC4, size: 2, name: "SET 0,H", func: op::unknown},
    OPCode { code: 0xC5, size: 2, name: "SET 0,L", func: op::unknown},
    OPCode { code: 0xC6, size: 2, name: "SET 0,(HL)", func: op::unknown},
    OPCode { code: 0xC7, size: 2, name: "SET 0,A", func: op::unknown},
    OPCode { code: 0xC8, size: 2, name: "SET 1,B", func: op::unknown},
    OPCode { code: 0xC9, size: 2, name: "SET 1,C", func: op::unknown},
    OPCode { code: 0xCA, size: 2, name: "SET 1,D", func: op::unknown},
    OPCode { code: 0xCB, size: 2, name: "SET 1,E", func: op::unknown},
    OPCode { code: 0xCC, size: 2, name: "SET 1,H", func: op::unknown},
    OPCode { code: 0xCD, size: 2, name: "SET 1,L", func: op::unknown},
    OPCode { code: 0xCE, size: 2, name: "SET 1,(HL)", func: op::unknown},
    OPCode { code: 0xCF, size: 2, name: "SET 1,A", func: op::unknown},
    ////////////// 0xDx
    OPCode { code: 0xD0, size: 2, name: "SET 2,B", func: op::unknown}, 
    OPCode { code: 0xD1, size: 2, name: "SET 2,C", func: op::unknown},
    OPCode { code: 0xD2, size: 2, name: "SET 2,D", func: op::unknown},
    OPCode { code: 0xD3, size: 2, name: "SET 2,E", func: op::unknown},
    OPCode { code: 0xD4, size: 2, name: "SET 2,H", func: op::unknown},
    OPCode { code: 0xD5, size: 2, name: "SET 2,L", func: op::unknown},
    OPCode { code: 0xD6, size: 2, name: "SET 2,(HL)", func: op::unknown},
    OPCode { code: 0xD7, size: 2, name: "SET 2,A", func: op::unknown},
    OPCode { code: 0xD8, size: 2, name: "SET 3,B", func: op::unknown},
    OPCode { code: 0xD9, size: 2, name: "SET 3,C", func: op::unknown},
    OPCode { code: 0xDA, size: 2, name: "SET 3,D", func: op::unknown},
    OPCode { code: 0xDB, size: 2, name: "SET 3,E", func: op::unknown},
    OPCode { code: 0xDC, size: 2, name: "SET 3,H", func: op::unknown},
    OPCode { code: 0xDD, size: 2, name: "SET 3,L", func: op::unknown},
    OPCode { code: 0xDE, size: 2, name: "SET 3,(HL)", func: op::unknown},
    OPCode { code: 0xDF, size: 2, name: "SET 3,A", func: op::unknown},
    ////////////// 0xEx
    OPCode { code: 0xE0, size: 2, name: "SET 4,B", func: op::unknown}, 
    OPCode { code: 0xE1, size: 2, name: "SET 4,C", func: op::unknown},
    OPCode { code: 0xE2, size: 2, name: "SET 4,D", func: op::unknown},
    OPCode { code: 0xE3, size: 2, name: "SET 4,E", func: op::unknown},
    OPCode { code: 0xE4, size: 2, name: "SET 4,H", func: op::unknown},
    OPCode { code: 0xE5, size: 2, name: "SET 4,L", func: op::unknown},
    OPCode { code: 0xE6, size: 2, name: "SET 4,(HL)", func: op::unknown},
    OPCode { code: 0xE7, size: 2, name: "SET 4,A", func: op::unknown},
    OPCode { code: 0xE8, size: 2, name: "SET 5,B", func: op::unknown},
    OPCode { code: 0xE9, size: 2, name: "SET 5,C", func: op::unknown},
    OPCode { code: 0xEA, size: 2, name: "SET 5,D", func: op::unknown},
    OPCode { code: 0xEB, size: 2, name: "SET 5,E", func: op::unknown},
    OPCode { code: 0xEC, size: 2, name: "SET 5,H", func: op::unknown},
    OPCode { code: 0xED, size: 2, name: "SET 5,L", func: op::unknown},
    OPCode { code: 0xEE, size: 2, name: "SET 5,(HL)", func: op::unknown},
    OPCode { code: 0xEF, size: 2, name: "SET 5,A", func: op::unknown},
    ////////////// 0xFx
    OPCode { code: 0xF0, size: 2, name: "SET 6,B", func: op::unknown}, 
    OPCode { code: 0xF1, size: 2, name: "SET 6,C", func: op::unknown},
    OPCode { code: 0xF2, size: 2, name: "SET 6,D", func: op::unknown},
    OPCode { code: 0xF3, size: 2, name: "SET 6,E", func: op::unknown},
    OPCode { code: 0xF4, size: 2, name: "SET 6,H", func: op::unknown},
    OPCode { code: 0xF5, size: 2, name: "SET 6,L", func: op::unknown},
    OPCode { code: 0xF6, size: 2, name: "SET 6,(HL)", func: op::unknown},
    OPCode { code: 0xF7, size: 2, name: "SET 6,A", func: op::unknown},
    OPCode { code: 0xF8, size: 2, name: "SET 7,B", func: op::unknown},
    OPCode { code: 0xF9, size: 2, name: "SET 7,C", func: op::unknown},
    OPCode { code: 0xFA, size: 2, name: "SET 7,D", func: op::unknown},
    OPCode { code: 0xFB, size: 2, name: "SET 7,E", func: op::unknown},
    OPCode { code: 0xFC, size: 2, name: "SET 7,H", func: op::unknown},
    OPCode { code: 0xFD, size: 2, name: "SET 7,L", func: op::unknown},
    OPCode { code: 0xFE, size: 2, name: "SET 7,(HL)", func: op::unknown},
    OPCode { code: 0xFF, size: 2, name: "SET 7,A", func: op::unknown},
];