use crate::gb::opcodes::opcode::OPCode;
use crate::gb::opcodes::ops;

pub static  OP_TABLE : [OPCode; 0x100] = [
    ////////////// 0x0x
    OPCode { code: 0x00, size: 1, name: "NOP", func: ops::control::nop}, 
    OPCode { code: 0x01, size: 3, name: "LD BC,d16", func: ops::loads::ld_bc_d16},
    OPCode { code: 0x02, size: 1, name: "LD (BC),A", func: ops::loads::ld_bc_a},
    OPCode { code: 0x03, size: 1, name: "INC BC", func: ops::errors::unknown},
    OPCode { code: 0x04, size: 1, name: "INC B", func: ops::math::inc_b},
    OPCode { code: 0x05, size: 1, name: "DEC B", func: ops::math::dec_b},
    OPCode { code: 0x06, size: 2, name: "LD B,d8", func: ops::loads::ld_b_d8},
    OPCode { code: 0x07, size: 1, name: "RLCA", func: ops::errors::unknown},
    OPCode { code: 0x08, size: 3, name: "LD (a16),SP", func: ops::loads::ld_a16_sp},
    OPCode { code: 0x09, size: 1, name: "ADD HL,BC", func: ops::errors::unknown},
    OPCode { code: 0x0A, size: 1, name: "LD A,(BC)", func: ops::loads::ld_a_bc},
    OPCode { code: 0x0B, size: 1, name: "DEC BC", func: ops::errors::unknown},
    OPCode { code: 0x0C, size: 1, name: "INC C", func: ops::math::inc_c},
    OPCode { code: 0x0D, size: 1, name: "DEC C", func: ops::math::dec_c},
    OPCode { code: 0x0E, size: 2, name: "LD C,d8", func: ops::loads::ld_c_d8},
    OPCode { code: 0x0F, size: 1, name: "RRCA", func: ops::errors::unknown},
    ////////////// 0x1x
    OPCode { code: 0x10, size: 2, name: "STOP 0", func: ops::control::stop}, 
    OPCode { code: 0x11, size: 3, name: "LD DE,d16", func: ops::loads::ld_de_d16},
    OPCode { code: 0x12, size: 1, name: "LD (DE),A", func: ops::loads::ld_de_a},
    OPCode { code: 0x13, size: 1, name: "INC DE", func: ops::errors::unknown},
    OPCode { code: 0x14, size: 1, name: "INC D", func: ops::math::inc_d},
    OPCode { code: 0x15, size: 1, name: "DEC D", func: ops::math::dec_d},
    OPCode { code: 0x16, size: 2, name: "LD D,d8", func: ops::loads::ld_d_d8},
    OPCode { code: 0x17, size: 1, name: "RLA", func: ops::errors::unknown},
    OPCode { code: 0x18, size: 2, name: "JR r8", func: ops::jumps::jr_r8},
    OPCode { code: 0x19, size: 1, name: "ADD HL,DE", func: ops::errors::unknown},
    OPCode { code: 0x1A, size: 1, name: "LD A,(DE)", func: ops::loads::ld_a_de},
    OPCode { code: 0x1B, size: 1, name: "DEC DE", func: ops::errors::unknown},
    OPCode { code: 0x1C, size: 1, name: "INC E", func: ops::math::inc_e},
    OPCode { code: 0x1D, size: 1, name: "DEC E", func: ops::math::dec_e},
    OPCode { code: 0x1E, size: 2, name: "LD E,d8", func: ops::loads::ld_e_d8},
    OPCode { code: 0x1F, size: 1, name: "RRA", func: ops::errors::unknown},
    ////////////// 0x2x
    OPCode { code: 0x20, size: 2, name: "JR NZ,r8", func: ops::jumps::jr_nz_r8},
    OPCode { code: 0x21, size: 3, name: "LD HL,d16", func: ops::loads::ld_hl_d16},
    OPCode { code: 0x22, size: 1, name: "LD (HL+),A", func: ops::loads::ld_hl_inc_a},
    OPCode { code: 0x23, size: 1, name: "INC HL", func: ops::errors::unknown},
    OPCode { code: 0x24, size: 1, name: "INC H", func: ops::math::inc_h},
    OPCode { code: 0x25, size: 1, name: "DEC H", func: ops::math::dec_h},
    OPCode { code: 0x26, size: 2, name: "LD H,d8", func: ops::loads::ld_h_d8},
    OPCode { code: 0x27, size: 1, name: "DAA", func: ops::errors::unknown},
    OPCode { code: 0x28, size: 2, name: "JR Z,r8", func: ops::jumps::jr_z_r8},
    OPCode { code: 0x29, size: 1, name: "ADD HL,HL", func: ops::errors::unknown},
    OPCode { code: 0x2A, size: 1, name: "LD A,(HL+)", func: ops::loads::ld_a_hl_inc},
    OPCode { code: 0x2B, size: 1, name: "DEC HL", func: ops::errors::unknown},
    OPCode { code: 0x2C, size: 1, name: "INC L", func: ops::math::inc_l},
    OPCode { code: 0x2D, size: 1, name: "DEC L", func: ops::math::dec_l},
    OPCode { code: 0x2E, size: 2, name: "LD L,d8", func: ops::loads::ld_l_d8},
    OPCode { code: 0x2F, size: 1, name: "CPL", func: ops::errors::unknown},
    ////////////// 0x3x
    OPCode { code: 0x30, size: 2, name: "JR NC,r8", func: ops::jumps::jr_nc_r8}, 
    OPCode { code: 0x31, size: 3, name: "LD SP,d16", func: ops::loads::ld_sp_d16},
    OPCode { code: 0x32, size: 1, name: "LD (HL-),A", func: ops::loads::ld_hl_dec_a},
    OPCode { code: 0x33, size: 1, name: "INC SP", func: ops::errors::unknown},
    OPCode { code: 0x34, size: 1, name: "INC (HL)", func: ops::math::inc_hl},
    OPCode { code: 0x35, size: 1, name: "DEC (HL)", func: ops::math::dec_hl},
    OPCode { code: 0x36, size: 2, name: "LD (HL),d8", func: ops::loads::ld_hl_d8},
    OPCode { code: 0x37, size: 1, name: "SCF", func: ops::errors::unknown},
    OPCode { code: 0x38, size: 2, name: "JR C,r8", func: ops::jumps::jr_c_r8},
    OPCode { code: 0x39, size: 1, name: "ADD HL,SP", func: ops::errors::unknown},
    OPCode { code: 0x3A, size: 1, name: "LD A,(HL-)", func: ops::loads::ld_a_hl_dec},
    OPCode { code: 0x3B, size: 1, name: "DEC SP", func: ops::errors::unknown},
    OPCode { code: 0x3C, size: 1, name: "INC A", func: ops::math::inc_a},
    OPCode { code: 0x3D, size: 1, name: "DEC A", func: ops::math::dec_a},
    OPCode { code: 0x3E, size: 2, name: "LD A,d8", func: ops::loads::ld_a_d8},
    OPCode { code: 0x3F, size: 1, name: "CCF", func: ops::errors::unknown},
    ////////////// 0x4x
    OPCode { code: 0x40, size: 1, name: "LD B,B", func: ops::errors::unknown}, 
    OPCode { code: 0x41, size: 1, name: "LD B,C", func: ops::errors::unknown},
    OPCode { code: 0x42, size: 1, name: "LD B,D", func: ops::errors::unknown},
    OPCode { code: 0x43, size: 1, name: "LD B,E", func: ops::errors::unknown},
    OPCode { code: 0x44, size: 1, name: "LD B,H", func: ops::errors::unknown},
    OPCode { code: 0x45, size: 1, name: "LD B,L", func: ops::errors::unknown},
    OPCode { code: 0x46, size: 1, name: "LD B,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x47, size: 1, name: "LD B,A", func: ops::errors::unknown},
    OPCode { code: 0x48, size: 1, name: "LD C,B", func: ops::errors::unknown},
    OPCode { code: 0x49, size: 1, name: "LD C,C", func: ops::errors::unknown},
    OPCode { code: 0x4A, size: 1, name: "LD C,D", func: ops::errors::unknown},
    OPCode { code: 0x4B, size: 1, name: "LD C,E", func: ops::errors::unknown},
    OPCode { code: 0x4C, size: 1, name: "LD C,H", func: ops::errors::unknown},
    OPCode { code: 0x4D, size: 1, name: "LD C,L", func: ops::errors::unknown},
    OPCode { code: 0x4E, size: 1, name: "LD C,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x4F, size: 1, name: "LD C,A", func: ops::errors::unknown},
    ////////////// 0x5x
    OPCode { code: 0x50, size: 1, name: "LD D,B", func: ops::errors::unknown}, 
    OPCode { code: 0x51, size: 1, name: "LD D,C", func: ops::errors::unknown},
    OPCode { code: 0x52, size: 1, name: "LD D,D", func: ops::errors::unknown},
    OPCode { code: 0x53, size: 1, name: "LD D,E", func: ops::errors::unknown},
    OPCode { code: 0x54, size: 1, name: "LD D,H", func: ops::errors::unknown},
    OPCode { code: 0x55, size: 1, name: "LD D,L", func: ops::errors::unknown},
    OPCode { code: 0x56, size: 1, name: "LD D,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x57, size: 1, name: "LD D,A", func: ops::errors::unknown},
    OPCode { code: 0x58, size: 1, name: "LD E,B", func: ops::errors::unknown},
    OPCode { code: 0x59, size: 1, name: "LD E,C", func: ops::errors::unknown},
    OPCode { code: 0x5A, size: 1, name: "LD E,D", func: ops::errors::unknown},
    OPCode { code: 0x5B, size: 1, name: "LD E,E", func: ops::errors::unknown},
    OPCode { code: 0x5C, size: 1, name: "LD E,H", func: ops::errors::unknown},
    OPCode { code: 0x5D, size: 1, name: "LD E,L", func: ops::errors::unknown},
    OPCode { code: 0x5E, size: 1, name: "LD E,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x5F, size: 1, name: "LD E,A", func: ops::errors::unknown},
    ////////////// 0x6x
    OPCode { code: 0x60, size: 1, name: "LD H,B", func: ops::errors::unknown}, 
    OPCode { code: 0x61, size: 1, name: "LD H,C", func: ops::errors::unknown},
    OPCode { code: 0x62, size: 1, name: "LD H,D", func: ops::errors::unknown},
    OPCode { code: 0x63, size: 1, name: "LD H,E", func: ops::errors::unknown},
    OPCode { code: 0x64, size: 1, name: "LD H,H", func: ops::errors::unknown},
    OPCode { code: 0x65, size: 1, name: "LD H,L", func: ops::errors::unknown},
    OPCode { code: 0x66, size: 1, name: "LD H,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x67, size: 1, name: "LD H,A", func: ops::errors::unknown},
    OPCode { code: 0x68, size: 1, name: "LD L,B", func: ops::errors::unknown},
    OPCode { code: 0x69, size: 1, name: "LD L,C", func: ops::errors::unknown},
    OPCode { code: 0x6A, size: 1, name: "LD L,D", func: ops::errors::unknown},
    OPCode { code: 0x6B, size: 1, name: "LD L,E", func: ops::errors::unknown},
    OPCode { code: 0x6C, size: 1, name: "LD L,H", func: ops::errors::unknown},
    OPCode { code: 0x6D, size: 1, name: "LD L,L", func: ops::errors::unknown},
    OPCode { code: 0x6E, size: 1, name: "LD L,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x6F, size: 1, name: "LD L,A", func: ops::errors::unknown},
    ////////////// 0x7x
    OPCode { code: 0x70, size: 1, name: "LD (HL),B", func: ops::errors::unknown}, 
    OPCode { code: 0x71, size: 1, name: "LD (HL),C", func: ops::errors::unknown},
    OPCode { code: 0x72, size: 1, name: "LD (HL),D", func: ops::errors::unknown},
    OPCode { code: 0x73, size: 1, name: "LD (HL),E", func: ops::errors::unknown},
    OPCode { code: 0x74, size: 1, name: "LD (HL),H", func: ops::errors::unknown},
    OPCode { code: 0x75, size: 1, name: "LD (HL),L", func: ops::errors::unknown},
    OPCode { code: 0x76, size: 1, name: "HALT", func: ops::control::halt},
    OPCode { code: 0x77, size: 1, name: "LD (HL),A", func: ops::errors::unknown},
    OPCode { code: 0x78, size: 1, name: "LD A,B", func: ops::errors::unknown},
    OPCode { code: 0x79, size: 1, name: "LD A,C", func: ops::errors::unknown},
    OPCode { code: 0x7A, size: 1, name: "LD A,D", func: ops::errors::unknown},
    OPCode { code: 0x7B, size: 1, name: "LD A,E", func: ops::errors::unknown},
    OPCode { code: 0x7C, size: 1, name: "LD A,H", func: ops::errors::unknown},
    OPCode { code: 0x7D, size: 1, name: "LD A,L", func: ops::errors::unknown},
    OPCode { code: 0x7E, size: 1, name: "LD A,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x7F, size: 1, name: "LD A,A", func: ops::errors::unknown},
    ////////////// 0x8x
    OPCode { code: 0x80, size: 1, name: "ADD A,B", func: ops::math::add_a_b}, 
    OPCode { code: 0x81, size: 1, name: "ADD A,C", func: ops::math::add_a_c},
    OPCode { code: 0x82, size: 1, name: "ADD A,D", func: ops::math::add_a_d},
    OPCode { code: 0x83, size: 1, name: "ADD A,E", func: ops::math::add_a_e},
    OPCode { code: 0x84, size: 1, name: "ADD A,H", func: ops::math::add_a_h},
    OPCode { code: 0x85, size: 1, name: "ADD A,L", func: ops::math::add_a_l},
    OPCode { code: 0x86, size: 1, name: "ADD A,(HL)", func: ops::math::add_a_hl},
    OPCode { code: 0x87, size: 1, name: "ADD A,A", func: ops::math::add_a_a},
    OPCode { code: 0x88, size: 1, name: "ADC A,B", func: ops::math::adc_a_b},
    OPCode { code: 0x89, size: 1, name: "ADC A,C", func: ops::math::adc_a_c},
    OPCode { code: 0x8A, size: 1, name: "ADC A,D", func: ops::math::adc_a_d},
    OPCode { code: 0x8B, size: 1, name: "ADC A,E", func: ops::math::adc_a_e},
    OPCode { code: 0x8C, size: 1, name: "ADC A,H", func: ops::math::adc_a_h},
    OPCode { code: 0x8D, size: 1, name: "ADC A,L", func: ops::math::adc_a_l},
    OPCode { code: 0x8E, size: 1, name: "ADC A,(HL)", func: ops::math::adc_a_hl},
    OPCode { code: 0x8F, size: 1, name: "ADC A,A", func: ops::math::adc_a_a},
    ////////////// 0x9x
    OPCode { code: 0x90, size: 1, name: "SUB B", func: ops::math::sub_b}, 
    OPCode { code: 0x91, size: 1, name: "SUB C", func: ops::math::sub_c},
    OPCode { code: 0x92, size: 1, name: "SUB D", func: ops::math::sub_d},
    OPCode { code: 0x93, size: 1, name: "SUB E", func: ops::math::sub_e},
    OPCode { code: 0x94, size: 1, name: "SUB H", func: ops::math::sub_h},
    OPCode { code: 0x95, size: 1, name: "SUB L", func: ops::math::sub_l},
    OPCode { code: 0x96, size: 1, name: "SUB (HL)", func: ops::math::sub_hl},
    OPCode { code: 0x97, size: 1, name: "SUB A", func: ops::math::sub_a},
    OPCode { code: 0x98, size: 1, name: "SBC A,B", func: ops::math::adc_a_b},
    OPCode { code: 0x99, size: 1, name: "SBC A,C", func: ops::math::sbc_a_c},
    OPCode { code: 0x9A, size: 1, name: "SBC A,D", func: ops::math::sbc_a_d},
    OPCode { code: 0x9B, size: 1, name: "SBC A,E", func: ops::math::sbc_a_e},
    OPCode { code: 0x9C, size: 1, name: "SBC A,H", func: ops::math::sbc_a_h},
    OPCode { code: 0x9D, size: 1, name: "SBC A,L", func: ops::math::sbc_a_l},
    OPCode { code: 0x9E, size: 1, name: "SBC A,(HL)", func: ops::math::sbc_a_hl},
    OPCode { code: 0x9F, size: 1, name: "SBC A,A", func: ops::math::sbc_a_a},
    ////////////// 0xAx
    OPCode { code: 0xA0, size: 1, name: "AND B", func: ops::math::and_b}, 
    OPCode { code: 0xA1, size: 1, name: "AND C", func: ops::math::and_c},
    OPCode { code: 0xA2, size: 1, name: "AND D", func: ops::math::and_d},
    OPCode { code: 0xA3, size: 1, name: "AND E", func: ops::math::and_e},
    OPCode { code: 0xA4, size: 1, name: "AND H", func: ops::math::and_h},
    OPCode { code: 0xA5, size: 1, name: "AND L", func: ops::math::and_l},
    OPCode { code: 0xA6, size: 1, name: "AND (HL)", func: ops::math::and_hl},
    OPCode { code: 0xA7, size: 1, name: "AND A", func: ops::math::and_a},
    OPCode { code: 0xA8, size: 1, name: "XOR B", func: ops::math::xor_b},
    OPCode { code: 0xA9, size: 1, name: "XOR C", func: ops::math::xor_c},
    OPCode { code: 0xAA, size: 1, name: "XOR D", func: ops::math::xor_d},
    OPCode { code: 0xAB, size: 1, name: "XOR E", func: ops::math::xor_e},
    OPCode { code: 0xAC, size: 1, name: "XOR H", func: ops::math::xor_h},
    OPCode { code: 0xAD, size: 1, name: "XOR L", func: ops::math::xor_l},
    OPCode { code: 0xAE, size: 1, name: "XOR (HL)", func: ops::math::xor_hl},
    OPCode { code: 0xAF, size: 1, name: "XOR A", func: ops::math::xor_a},
    ////////////// 0xBx
    OPCode { code: 0xB0, size: 1, name: "OR B", func: ops::math::or_b}, 
    OPCode { code: 0xB1, size: 1, name: "OR C", func: ops::math::or_c},
    OPCode { code: 0xB2, size: 1, name: "OR D", func: ops::math::or_d},
    OPCode { code: 0xB3, size: 1, name: "OR E", func: ops::math::or_e},
    OPCode { code: 0xB4, size: 1, name: "OR H", func: ops::math::or_h},
    OPCode { code: 0xB5, size: 1, name: "OR L", func: ops::math::or_l},
    OPCode { code: 0xB6, size: 1, name: "OR (HL)", func: ops::math::or_hl},
    OPCode { code: 0xB7, size: 1, name: "OR A", func: ops::math::or_a},
    OPCode { code: 0xB8, size: 1, name: "CP B", func: ops::math::cp_b},
    OPCode { code: 0xB9, size: 1, name: "CP C", func: ops::math::cp_c},
    OPCode { code: 0xBA, size: 1, name: "CP D", func: ops::math::cp_d},
    OPCode { code: 0xBB, size: 1, name: "CP E", func: ops::math::cp_e},
    OPCode { code: 0xBC, size: 1, name: "CP H", func: ops::math::cp_h},
    OPCode { code: 0xBD, size: 1, name: "CP L", func: ops::math::cp_l},
    OPCode { code: 0xBE, size: 1, name: "CP (HL)", func: ops::math::cp_hl},
    OPCode { code: 0xBF, size: 1, name: "CP A", func: ops::math::cp_a},
    ////////////// 0xCx
    OPCode { code: 0xC0, size: 1, name: "RET NZ", func: ops::jumps::ret_nz},
    OPCode { code: 0xC1, size: 2, name: "POP BC", func: ops::loads::pop_bc},
    OPCode { code: 0xC2, size: 3, name: "JP NZ,a16", func: ops::jumps::jp_nz_a16},
    OPCode { code: 0xC3, size: 3, name: "JP a16", func: ops::jumps::jp_a16},
    OPCode { code: 0xC4, size: 3, name: "CALL NZ,a16", func: ops::jumps::call_nz_a16},
    OPCode { code: 0xC5, size: 1, name: "PUSH BC", func: ops::loads::push_bc},
    OPCode { code: 0xC6, size: 2, name: "ADD A,d8", func: ops::math::add_a_d8},
    OPCode { code: 0xC7, size: 1, name: "RST 00H", func: ops::jumps::rst_00h},
    OPCode { code: 0xC8, size: 1, name: "RET Z", func: ops::jumps::ret_z},
    OPCode { code: 0xC9, size: 1, name: "RET", func: ops::jumps::ret},
    OPCode { code: 0xCA, size: 3, name: "JP Z,a16", func: ops::jumps::jp_z_a16},
    OPCode { code: 0xCB, size: 1, name: "PREFIX CB", func: ops::control::prefix_cb},
    OPCode { code: 0xCC, size: 3, name: "CALL Z,a16", func: ops::jumps::call_z_a16},
    OPCode { code: 0xCD, size: 3, name: "CALL a16", func: ops::jumps::call_a16}, 
    OPCode { code: 0xCE, size: 2, name: "ADC A,d8", func: ops::math::adc_a_d8},
    OPCode { code: 0xCF, size: 1, name: "RST 08H", func: ops::jumps::rst_08h},
    ////////////// 0xDx
    OPCode { code: 0xD0, size: 1, name: "RET NC", func: ops::jumps::ret_nc},
    OPCode { code: 0xD1, size: 1, name: "POP DE", func: ops::loads::pop_de},
    OPCode { code: 0xD2, size: 3, name: "JP NC,a16", func: ops::jumps::jp_nc_a16},
    OPCode { code: 0xD3, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xD4, size: 3, name: "CALL NC,a16", func: ops::jumps::call_nc_a16},
    OPCode { code: 0xD5, size: 1, name: "PUSH DE", func: ops::loads::push_de},
    OPCode { code: 0xD6, size: 2, name: "SUB d8", func: ops::math::sub_d8},
    OPCode { code: 0xD7, size: 1, name: "RST 10H", func: ops::jumps::rst_10h},
    OPCode { code: 0xD8, size: 1, name: "RET C", func: ops::jumps::ret_c},
    OPCode { code: 0xD9, size: 1, name: "RETI", func: ops::jumps::reti},
    OPCode { code: 0xDA, size: 3, name: "JP C,a16", func: ops::jumps::jp_c_a16},
    OPCode { code: 0xDB, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xDC, size: 3, name: "CALL C,a16", func: ops::jumps::call_c_a16},
    OPCode { code: 0xDD, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xDE, size: 2, name: "SBC A,d8", func: ops::math::sbc_a_d8},
    OPCode { code: 0xDF, size: 1, name: "RST 18H", func: ops::jumps::rst_18h},
    ////////////// 0xEx
    OPCode { code: 0xE0, size: 2, name: "LDH (a8),A", func: ops::loads::ldh_a8_a}, 
    OPCode { code: 0xE1, size: 1, name: "POP HL", func: ops::loads::pop_hl},
    OPCode { code: 0xE2, size: 2, name: "LD (C),A", func: ops::loads::ld_addr_c_a},
    OPCode { code: 0xE3, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xE4, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xE5, size: 1, name: "PUSH HL", func: ops::loads::push_hl},
    OPCode { code: 0xE6, size: 2, name: "AND d8", func: ops::math::and_d8},
    OPCode { code: 0xE7, size: 1, name: "RST 20H", func: ops::jumps::rst_20h},
    OPCode { code: 0xE8, size: 2, name: "ADD SP,r8", func: ops::errors::unknown},
    OPCode { code: 0xE9, size: 1, name: "JP (HL)", func: ops::jumps::jp_hl},
    OPCode { code: 0xEA, size: 3, name: "LD (a16),A", func: ops::loads::ld_a16_a},
    OPCode { code: 0xEB, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xEC, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xED, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xEE, size: 2, name: "XOR d8", func: ops::math::xor_d8},
    OPCode { code: 0xEF, size: 1, name: "RST 28H", func: ops::jumps::rst_28h},
    ////////////// 0xFx
    OPCode { code: 0xF0, size: 2, name: "LDH A,(a8)", func: ops::loads::ldh_a_a8}, 
    OPCode { code: 0xF1, size: 1, name: "POP AF", func: ops::loads::pop_af},
    OPCode { code: 0xF2, size: 2, name: "LD A,(C)", func: ops::loads::ld_a_addr_c},
    OPCode { code: 0xF3, size: 1, name: "DI", func: ops::control::di},
    OPCode { code: 0xF4, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xF5, size: 1, name: "PUSH AF", func: ops::loads::push_af},
    OPCode { code: 0xF6, size: 2, name: "OR d8", func: ops::math::or_d8},
    OPCode { code: 0xF7, size: 1, name: "RST 30H", func: ops::jumps::rst_30h},
    OPCode { code: 0xF8, size: 2, name: "LD HL,SP+r8", func: ops::loads::ld_hl_sp_plus_r8},
    OPCode { code: 0xF9, size: 1, name: "LD SP,HL", func: ops::loads::ld_sp_hl},
    OPCode { code: 0xFA, size: 3, name: "LD A,(a16)", func: ops::loads::ld_a_a16},
    OPCode { code: 0xFB, size: 1, name: "EI", func: ops::control::ei},
    OPCode { code: 0xFC, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xFD, size: 0, name: "UNUSED", func: ops::errors::unused},
    OPCode { code: 0xFE, size: 2, name: "CP d8", func: ops::math::cp_d8},
    OPCode { code: 0xFF, size: 1, name: "RST 38H", func: ops::jumps::rst_38h},
];


pub static CB_OP_TABLE : [OPCode; 0x100] = [
    ////////////// 0x0x
    OPCode { code: 0x00, size: 2, name: "RLC B", func: ops::errors::unknown}, 
    OPCode { code: 0x01, size: 2, name: "RLC C", func: ops::errors::unknown},
    OPCode { code: 0x02, size: 2, name: "RLC D", func: ops::errors::unknown},
    OPCode { code: 0x03, size: 2, name: "RLC E", func: ops::errors::unknown},
    OPCode { code: 0x04, size: 2, name: "RLC H", func: ops::errors::unknown},
    OPCode { code: 0x05, size: 2, name: "RLC L", func: ops::errors::unknown},
    OPCode { code: 0x06, size: 2, name: "RLC (HL)", func: ops::errors::unknown},
    OPCode { code: 0x07, size: 2, name: "RLC A", func: ops::errors::unknown},
    OPCode { code: 0x08, size: 2, name: "RRC B", func: ops::errors::unknown},
    OPCode { code: 0x09, size: 2, name: "RRC C", func: ops::errors::unknown},
    OPCode { code: 0x0A, size: 2, name: "RRC D", func: ops::errors::unknown},
    OPCode { code: 0x0B, size: 2, name: "RRC E", func: ops::errors::unknown},
    OPCode { code: 0x0C, size: 2, name: "RRC H", func: ops::errors::unknown},
    OPCode { code: 0x0D, size: 2, name: "RRC L", func: ops::errors::unknown},
    OPCode { code: 0x0E, size: 2, name: "RRC (HL)", func: ops::errors::unknown},
    OPCode { code: 0x0F, size: 2, name: "RRC A", func: ops::errors::unknown},
    ////////////// 0x1x
    OPCode { code: 0x10, size: 2, name: "RL B", func: ops::errors::unknown}, 
    OPCode { code: 0x11, size: 2, name: "RL C", func: ops::errors::unknown},
    OPCode { code: 0x12, size: 2, name: "RL D", func: ops::errors::unknown},
    OPCode { code: 0x13, size: 2, name: "RL E", func: ops::errors::unknown},
    OPCode { code: 0x14, size: 2, name: "RL H", func: ops::errors::unknown},
    OPCode { code: 0x15, size: 2, name: "RL L", func: ops::errors::unknown},
    OPCode { code: 0x16, size: 2, name: "RL (HL)", func: ops::errors::unknown},
    OPCode { code: 0x17, size: 2, name: "RL A", func: ops::errors::unknown},
    OPCode { code: 0x18, size: 2, name: "RR B", func: ops::errors::unknown},
    OPCode { code: 0x19, size: 2, name: "RR C", func: ops::errors::unknown},
    OPCode { code: 0x1A, size: 2, name: "RR D", func: ops::errors::unknown},
    OPCode { code: 0x1B, size: 2, name: "RR E", func: ops::errors::unknown},
    OPCode { code: 0x1C, size: 2, name: "RR H", func: ops::errors::unknown},
    OPCode { code: 0x1D, size: 2, name: "RR L", func: ops::errors::unknown},
    OPCode { code: 0x1E, size: 2, name: "RR (HL)", func: ops::errors::unknown},
    OPCode { code: 0x1F, size: 2, name: "RR A", func: ops::errors::unknown},
    ////////////// 0x2x
    OPCode { code: 0x20, size: 2, name: "SLA B", func: ops::errors::unknown}, 
    OPCode { code: 0x21, size: 2, name: "SLA C", func: ops::errors::unknown},
    OPCode { code: 0x22, size: 2, name: "SLA D", func: ops::errors::unknown},
    OPCode { code: 0x23, size: 2, name: "SLA E", func: ops::errors::unknown},
    OPCode { code: 0x24, size: 2, name: "SLA H", func: ops::errors::unknown},
    OPCode { code: 0x25, size: 2, name: "SLA L", func: ops::errors::unknown},
    OPCode { code: 0x26, size: 2, name: "SLA (HL)", func: ops::errors::unknown},
    OPCode { code: 0x27, size: 2, name: "SLA A", func: ops::errors::unknown},
    OPCode { code: 0x28, size: 2, name: "SRA B", func: ops::errors::unknown},
    OPCode { code: 0x29, size: 2, name: "SRA C", func: ops::errors::unknown},
    OPCode { code: 0x2A, size: 2, name: "SRA D", func: ops::errors::unknown},
    OPCode { code: 0x2B, size: 2, name: "SRA E", func: ops::errors::unknown},
    OPCode { code: 0x2C, size: 2, name: "SRA H", func: ops::errors::unknown},
    OPCode { code: 0x2D, size: 2, name: "SRA L", func: ops::errors::unknown},
    OPCode { code: 0x2E, size: 2, name: "SRA (HL)", func: ops::errors::unknown},
    OPCode { code: 0x2F, size: 2, name: "SRA A", func: ops::errors::unknown},
    ////////////// 0x3x
    OPCode { code: 0x30, size: 2, name: "SWAP B", func: ops::errors::unknown}, 
    OPCode { code: 0x31, size: 2, name: "SWAP C", func: ops::errors::unknown},
    OPCode { code: 0x32, size: 2, name: "SWAP D", func: ops::errors::unknown},
    OPCode { code: 0x33, size: 2, name: "SWAP E", func: ops::errors::unknown},
    OPCode { code: 0x34, size: 2, name: "SWAP H", func: ops::errors::unknown},
    OPCode { code: 0x35, size: 2, name: "SWAP L", func: ops::errors::unknown},
    OPCode { code: 0x36, size: 2, name: "SWAP (HL)", func: ops::errors::unknown},
    OPCode { code: 0x37, size: 2, name: "SWAP A", func: ops::errors::unknown},
    OPCode { code: 0x38, size: 2, name: "SRL B", func: ops::errors::unknown},
    OPCode { code: 0x39, size: 2, name: "SRL C", func: ops::errors::unknown},
    OPCode { code: 0x3A, size: 2, name: "SRL D", func: ops::errors::unknown},
    OPCode { code: 0x3B, size: 2, name: "SRL E", func: ops::errors::unknown},
    OPCode { code: 0x3C, size: 2, name: "SRL H", func: ops::errors::unknown},
    OPCode { code: 0x3D, size: 2, name: "SRL L", func: ops::errors::unknown},
    OPCode { code: 0x3E, size: 2, name: "SRL (HL)", func: ops::errors::unknown},
    OPCode { code: 0x3F, size: 2, name: "SRL A", func: ops::errors::unknown},
    ////////////// 0x4x
    OPCode { code: 0x40, size: 2, name: "BIT 0,B", func: ops::errors::unknown}, 
    OPCode { code: 0x41, size: 2, name: "BIT 0,C", func: ops::errors::unknown},
    OPCode { code: 0x42, size: 2, name: "BIT 0,D", func: ops::errors::unknown},
    OPCode { code: 0x43, size: 2, name: "BIT 0,E", func: ops::errors::unknown},
    OPCode { code: 0x44, size: 2, name: "BIT 0,H", func: ops::errors::unknown},
    OPCode { code: 0x45, size: 2, name: "BIT 0,L", func: ops::errors::unknown},
    OPCode { code: 0x46, size: 2, name: "BIT 0,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x47, size: 2, name: "BIT 0,A", func: ops::errors::unknown},
    OPCode { code: 0x48, size: 2, name: "BIT 1,B", func: ops::errors::unknown},
    OPCode { code: 0x49, size: 2, name: "BIT 1,C", func: ops::errors::unknown},
    OPCode { code: 0x4A, size: 2, name: "BIT 1,D", func: ops::errors::unknown},
    OPCode { code: 0x4B, size: 2, name: "BIT 1,E", func: ops::errors::unknown},
    OPCode { code: 0x4C, size: 2, name: "BIT 1,H", func: ops::errors::unknown},
    OPCode { code: 0x4D, size: 2, name: "BIT 1,L", func: ops::errors::unknown},
    OPCode { code: 0x4E, size: 2, name: "BIT 1,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x4F, size: 2, name: "BIT 1,A", func: ops::errors::unknown},
    ////////////// 0x5x
    OPCode { code: 0x50, size: 2, name: "BIT 2,B", func: ops::errors::unknown}, 
    OPCode { code: 0x51, size: 2, name: "BIT 2,C", func: ops::errors::unknown},
    OPCode { code: 0x52, size: 2, name: "BIT 2,D", func: ops::errors::unknown},
    OPCode { code: 0x53, size: 2, name: "BIT 2,E", func: ops::errors::unknown},
    OPCode { code: 0x54, size: 2, name: "BIT 2,H", func: ops::errors::unknown},
    OPCode { code: 0x55, size: 2, name: "BIT 2,L", func: ops::errors::unknown},
    OPCode { code: 0x56, size: 2, name: "BIT 2,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x57, size: 2, name: "BIT 2,A", func: ops::errors::unknown},
    OPCode { code: 0x58, size: 2, name: "BIT 3,B", func: ops::errors::unknown},
    OPCode { code: 0x59, size: 2, name: "BIT 3,C", func: ops::errors::unknown},
    OPCode { code: 0x5A, size: 2, name: "BIT 3,D", func: ops::errors::unknown},
    OPCode { code: 0x5B, size: 2, name: "BIT 3,E", func: ops::errors::unknown},
    OPCode { code: 0x5C, size: 2, name: "BIT 3,H", func: ops::errors::unknown},
    OPCode { code: 0x5D, size: 2, name: "BIT 3,L", func: ops::errors::unknown},
    OPCode { code: 0x5E, size: 2, name: "BIT 3,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x5F, size: 2, name: "BIT 3,A", func: ops::errors::unknown},
    ////////////// 0x6x
    OPCode { code: 0x60, size: 2, name: "BIT 4,B", func: ops::errors::unknown}, 
    OPCode { code: 0x61, size: 2, name: "BIT 4,C", func: ops::errors::unknown},
    OPCode { code: 0x62, size: 2, name: "BIT 4,D", func: ops::errors::unknown},
    OPCode { code: 0x63, size: 2, name: "BIT 4,E", func: ops::errors::unknown},
    OPCode { code: 0x64, size: 2, name: "BIT 4,H", func: ops::errors::unknown},
    OPCode { code: 0x65, size: 2, name: "BIT 4,L", func: ops::errors::unknown},
    OPCode { code: 0x66, size: 2, name: "BIT 4,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x67, size: 2, name: "BIT 4,A", func: ops::errors::unknown},
    OPCode { code: 0x68, size: 2, name: "BIT 5,B", func: ops::errors::unknown},
    OPCode { code: 0x69, size: 2, name: "BIT 5,C", func: ops::errors::unknown},
    OPCode { code: 0x6A, size: 2, name: "BIT 5,D", func: ops::errors::unknown},
    OPCode { code: 0x6B, size: 2, name: "BIT 5,E", func: ops::errors::unknown},
    OPCode { code: 0x6C, size: 2, name: "BIT 5,H", func: ops::errors::unknown},
    OPCode { code: 0x6D, size: 2, name: "BIT 5,L", func: ops::errors::unknown},
    OPCode { code: 0x6E, size: 2, name: "BIT 5,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x6F, size: 2, name: "BIT 5,A", func: ops::errors::unknown},
    ////////////// 0x7x
    OPCode { code: 0x70, size: 2, name: "BIT 6,B", func: ops::errors::unknown}, 
    OPCode { code: 0x71, size: 2, name: "BIT 6,C", func: ops::errors::unknown},
    OPCode { code: 0x72, size: 2, name: "BIT 6,D", func: ops::errors::unknown},
    OPCode { code: 0x73, size: 2, name: "BIT 6,E", func: ops::errors::unknown},
    OPCode { code: 0x74, size: 2, name: "BIT 6,H", func: ops::errors::unknown},
    OPCode { code: 0x75, size: 2, name: "BIT 6,L", func: ops::errors::unknown},
    OPCode { code: 0x76, size: 2, name: "BIT 6,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x77, size: 2, name: "BIT 6,A", func: ops::errors::unknown},
    OPCode { code: 0x78, size: 2, name: "BIT 7,B", func: ops::errors::unknown},
    OPCode { code: 0x79, size: 2, name: "BIT 7,C", func: ops::errors::unknown},
    OPCode { code: 0x7A, size: 2, name: "BIT 7,D", func: ops::errors::unknown},
    OPCode { code: 0x7B, size: 2, name: "BIT 7,E", func: ops::errors::unknown},
    OPCode { code: 0x7C, size: 2, name: "BIT 7,H", func: ops::errors::unknown},
    OPCode { code: 0x7D, size: 2, name: "BIT 7,L", func: ops::errors::unknown},
    OPCode { code: 0x7E, size: 2, name: "BIT 7,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x7F, size: 2, name: "BIT 7,A", func: ops::errors::unknown},
    ////////////// 0x8x
    OPCode { code: 0x80, size: 2, name: "RES 0,B", func: ops::errors::unknown}, 
    OPCode { code: 0x81, size: 2, name: "RES 0,C", func: ops::errors::unknown},
    OPCode { code: 0x82, size: 2, name: "RES 0,D", func: ops::errors::unknown},
    OPCode { code: 0x83, size: 2, name: "RES 0,E", func: ops::errors::unknown},
    OPCode { code: 0x84, size: 2, name: "RES 0,H", func: ops::errors::unknown},
    OPCode { code: 0x85, size: 2, name: "RES 0,L", func: ops::errors::unknown},
    OPCode { code: 0x86, size: 2, name: "RES 0,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x87, size: 2, name: "RES 0,A", func: ops::errors::unknown},
    OPCode { code: 0x88, size: 2, name: "RES 1,B", func: ops::errors::unknown},
    OPCode { code: 0x89, size: 2, name: "RES 1,C", func: ops::errors::unknown},
    OPCode { code: 0x8A, size: 2, name: "RES 1,D", func: ops::errors::unknown},
    OPCode { code: 0x8B, size: 2, name: "RES 1,E", func: ops::errors::unknown},
    OPCode { code: 0x8C, size: 2, name: "RES 1,H", func: ops::errors::unknown},
    OPCode { code: 0x8D, size: 2, name: "RES 1,L", func: ops::errors::unknown},
    OPCode { code: 0x8E, size: 2, name: "RES 1,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x8F, size: 2, name: "RES 1,A", func: ops::errors::unknown},
    ////////////// 0x9x
    OPCode { code: 0x90, size: 2, name: "RES 2,B", func: ops::errors::unknown}, 
    OPCode { code: 0x91, size: 2, name: "RES 2,C", func: ops::errors::unknown},
    OPCode { code: 0x92, size: 2, name: "RES 2,D", func: ops::errors::unknown},
    OPCode { code: 0x93, size: 2, name: "RES 2,E", func: ops::errors::unknown},
    OPCode { code: 0x94, size: 2, name: "RES 2,H", func: ops::errors::unknown},
    OPCode { code: 0x95, size: 2, name: "RES 2,L", func: ops::errors::unknown},
    OPCode { code: 0x96, size: 2, name: "RES 2,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x97, size: 2, name: "RES 2,A", func: ops::errors::unknown},
    OPCode { code: 0x98, size: 2, name: "RES 3,B", func: ops::errors::unknown},
    OPCode { code: 0x99, size: 2, name: "RES 3,C", func: ops::errors::unknown},
    OPCode { code: 0x9A, size: 2, name: "RES 3,D", func: ops::errors::unknown},
    OPCode { code: 0x9B, size: 2, name: "RES 3,E", func: ops::errors::unknown},
    OPCode { code: 0x9C, size: 2, name: "RES 3,H", func: ops::errors::unknown},
    OPCode { code: 0x9D, size: 2, name: "RES 3,L", func: ops::errors::unknown},
    OPCode { code: 0x9E, size: 2, name: "RES 3,(HL)", func: ops::errors::unknown},
    OPCode { code: 0x9F, size: 2, name: "RES 3,A", func: ops::errors::unknown},
    ////////////// 0xAx
    OPCode { code: 0xA0, size: 2, name: "RES 4,B", func: ops::errors::unknown}, 
    OPCode { code: 0xA1, size: 2, name: "RES 4,C", func: ops::errors::unknown},
    OPCode { code: 0xA2, size: 2, name: "RES 4,D", func: ops::errors::unknown},
    OPCode { code: 0xA3, size: 2, name: "RES 4,E", func: ops::errors::unknown},
    OPCode { code: 0xA4, size: 2, name: "RES 4,H", func: ops::errors::unknown},
    OPCode { code: 0xA5, size: 2, name: "RES 4,L", func: ops::errors::unknown},
    OPCode { code: 0xA6, size: 2, name: "RES 4,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xA7, size: 2, name: "RES 4,A", func: ops::errors::unknown},
    OPCode { code: 0xA8, size: 2, name: "RES 5,B", func: ops::errors::unknown},
    OPCode { code: 0xA9, size: 2, name: "RES 5,C", func: ops::errors::unknown},
    OPCode { code: 0xAA, size: 2, name: "RES 5,D", func: ops::errors::unknown},
    OPCode { code: 0xAB, size: 2, name: "RES 5,E", func: ops::errors::unknown},
    OPCode { code: 0xAC, size: 2, name: "RES 5,H", func: ops::errors::unknown},
    OPCode { code: 0xAD, size: 2, name: "RES 5,L", func: ops::errors::unknown},
    OPCode { code: 0xAE, size: 2, name: "RES 5,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xAF, size: 2, name: "RES 5,A", func: ops::errors::unknown},
    ////////////// 0xBx
    OPCode { code: 0xB0, size: 2, name: "RES 6,B", func: ops::errors::unknown}, 
    OPCode { code: 0xB1, size: 2, name: "RES 6,C", func: ops::errors::unknown},
    OPCode { code: 0xB2, size: 2, name: "RES 6,D", func: ops::errors::unknown},
    OPCode { code: 0xB3, size: 2, name: "RES 6,E", func: ops::errors::unknown},
    OPCode { code: 0xB4, size: 2, name: "RES 6,H", func: ops::errors::unknown},
    OPCode { code: 0xB5, size: 2, name: "RES 6,L", func: ops::errors::unknown},
    OPCode { code: 0xB6, size: 2, name: "RES 6,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xB7, size: 2, name: "RES 6,A", func: ops::errors::unknown},
    OPCode { code: 0xB8, size: 2, name: "RES 7,B", func: ops::errors::unknown},
    OPCode { code: 0xB9, size: 2, name: "RES 7,C", func: ops::errors::unknown},
    OPCode { code: 0xBA, size: 2, name: "RES 7,D", func: ops::errors::unknown},
    OPCode { code: 0xBB, size: 2, name: "RES 7,E", func: ops::errors::unknown},
    OPCode { code: 0xBC, size: 2, name: "RES 7,H", func: ops::errors::unknown},
    OPCode { code: 0xBD, size: 2, name: "RES 7,L", func: ops::errors::unknown},
    OPCode { code: 0xBE, size: 2, name: "RES 7,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xBF, size: 2, name: "RES 7,A", func: ops::errors::unknown},
    ////////////// 0xCx
    OPCode { code: 0xC0, size: 2, name: "SET 0,B", func: ops::errors::unknown}, 
    OPCode { code: 0xC1, size: 2, name: "SET 0,C", func: ops::errors::unknown},
    OPCode { code: 0xC2, size: 2, name: "SET 0,D", func: ops::errors::unknown},
    OPCode { code: 0xC3, size: 2, name: "SET 0,E", func: ops::errors::unknown},
    OPCode { code: 0xC4, size: 2, name: "SET 0,H", func: ops::errors::unknown},
    OPCode { code: 0xC5, size: 2, name: "SET 0,L", func: ops::errors::unknown},
    OPCode { code: 0xC6, size: 2, name: "SET 0,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xC7, size: 2, name: "SET 0,A", func: ops::errors::unknown},
    OPCode { code: 0xC8, size: 2, name: "SET 1,B", func: ops::errors::unknown},
    OPCode { code: 0xC9, size: 2, name: "SET 1,C", func: ops::errors::unknown},
    OPCode { code: 0xCA, size: 2, name: "SET 1,D", func: ops::errors::unknown},
    OPCode { code: 0xCB, size: 2, name: "SET 1,E", func: ops::errors::unknown},
    OPCode { code: 0xCC, size: 2, name: "SET 1,H", func: ops::errors::unknown},
    OPCode { code: 0xCD, size: 2, name: "SET 1,L", func: ops::errors::unknown},
    OPCode { code: 0xCE, size: 2, name: "SET 1,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xCF, size: 2, name: "SET 1,A", func: ops::errors::unknown},
    ////////////// 0xDx
    OPCode { code: 0xD0, size: 2, name: "SET 2,B", func: ops::errors::unknown}, 
    OPCode { code: 0xD1, size: 2, name: "SET 2,C", func: ops::errors::unknown},
    OPCode { code: 0xD2, size: 2, name: "SET 2,D", func: ops::errors::unknown},
    OPCode { code: 0xD3, size: 2, name: "SET 2,E", func: ops::errors::unknown},
    OPCode { code: 0xD4, size: 2, name: "SET 2,H", func: ops::errors::unknown},
    OPCode { code: 0xD5, size: 2, name: "SET 2,L", func: ops::errors::unknown},
    OPCode { code: 0xD6, size: 2, name: "SET 2,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xD7, size: 2, name: "SET 2,A", func: ops::errors::unknown},
    OPCode { code: 0xD8, size: 2, name: "SET 3,B", func: ops::errors::unknown},
    OPCode { code: 0xD9, size: 2, name: "SET 3,C", func: ops::errors::unknown},
    OPCode { code: 0xDA, size: 2, name: "SET 3,D", func: ops::errors::unknown},
    OPCode { code: 0xDB, size: 2, name: "SET 3,E", func: ops::errors::unknown},
    OPCode { code: 0xDC, size: 2, name: "SET 3,H", func: ops::errors::unknown},
    OPCode { code: 0xDD, size: 2, name: "SET 3,L", func: ops::errors::unknown},
    OPCode { code: 0xDE, size: 2, name: "SET 3,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xDF, size: 2, name: "SET 3,A", func: ops::errors::unknown},
    ////////////// 0xEx
    OPCode { code: 0xE0, size: 2, name: "SET 4,B", func: ops::errors::unknown}, 
    OPCode { code: 0xE1, size: 2, name: "SET 4,C", func: ops::errors::unknown},
    OPCode { code: 0xE2, size: 2, name: "SET 4,D", func: ops::errors::unknown},
    OPCode { code: 0xE3, size: 2, name: "SET 4,E", func: ops::errors::unknown},
    OPCode { code: 0xE4, size: 2, name: "SET 4,H", func: ops::errors::unknown},
    OPCode { code: 0xE5, size: 2, name: "SET 4,L", func: ops::errors::unknown},
    OPCode { code: 0xE6, size: 2, name: "SET 4,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xE7, size: 2, name: "SET 4,A", func: ops::errors::unknown},
    OPCode { code: 0xE8, size: 2, name: "SET 5,B", func: ops::errors::unknown},
    OPCode { code: 0xE9, size: 2, name: "SET 5,C", func: ops::errors::unknown},
    OPCode { code: 0xEA, size: 2, name: "SET 5,D", func: ops::errors::unknown},
    OPCode { code: 0xEB, size: 2, name: "SET 5,E", func: ops::errors::unknown},
    OPCode { code: 0xEC, size: 2, name: "SET 5,H", func: ops::errors::unknown},
    OPCode { code: 0xED, size: 2, name: "SET 5,L", func: ops::errors::unknown},
    OPCode { code: 0xEE, size: 2, name: "SET 5,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xEF, size: 2, name: "SET 5,A", func: ops::errors::unknown},
    ////////////// 0xFx
    OPCode { code: 0xF0, size: 2, name: "SET 6,B", func: ops::errors::unknown}, 
    OPCode { code: 0xF1, size: 2, name: "SET 6,C", func: ops::errors::unknown},
    OPCode { code: 0xF2, size: 2, name: "SET 6,D", func: ops::errors::unknown},
    OPCode { code: 0xF3, size: 2, name: "SET 6,E", func: ops::errors::unknown},
    OPCode { code: 0xF4, size: 2, name: "SET 6,H", func: ops::errors::unknown},
    OPCode { code: 0xF5, size: 2, name: "SET 6,L", func: ops::errors::unknown},
    OPCode { code: 0xF6, size: 2, name: "SET 6,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xF7, size: 2, name: "SET 6,A", func: ops::errors::unknown},
    OPCode { code: 0xF8, size: 2, name: "SET 7,B", func: ops::errors::unknown},
    OPCode { code: 0xF9, size: 2, name: "SET 7,C", func: ops::errors::unknown},
    OPCode { code: 0xFA, size: 2, name: "SET 7,D", func: ops::errors::unknown},
    OPCode { code: 0xFB, size: 2, name: "SET 7,E", func: ops::errors::unknown},
    OPCode { code: 0xFC, size: 2, name: "SET 7,H", func: ops::errors::unknown},
    OPCode { code: 0xFD, size: 2, name: "SET 7,L", func: ops::errors::unknown},
    OPCode { code: 0xFE, size: 2, name: "SET 7,(HL)", func: ops::errors::unknown},
    OPCode { code: 0xFF, size: 2, name: "SET 7,A", func: ops::errors::unknown},
];